/**
 * Comprehensive Microservices Ecosystem Configuration
 *
 * This example demonstrates a production-ready microservices setup
 * with multiple services, databases, caches, and monitoring.
 */

export default {
  apps: [
    // API Gateway
    {
      name: 'api-gateway',
      script: './services/gateway/index.js',
      instances: 4,
      exec_mode: 'cluster',
      watch: false,
      max_memory_restart: '1G',
      min_uptime: 10000,
      max_restarts: 10,
      autorestart: true,
      restart_delay: 4000,
      env: {
        NODE_ENV: 'development',
        PORT: 8000,
        SERVICE_NAME: 'api-gateway',
        LOG_LEVEL: 'debug',
        RATE_LIMIT: '1000',
        TIMEOUT: '30000',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 8000,
        SERVICE_NAME: 'api-gateway',
        LOG_LEVEL: 'info',
        RATE_LIMIT: '10000',
        TIMEOUT: '60000',
      },
      error_file: './logs/gateway-error.log',
      out_file: './logs/gateway-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },

    // Authentication Service
    {
      name: 'auth-service',
      script: './services/auth/server.js',
      instances: 3,
      exec_mode: 'cluster',
      max_memory_restart: '512M',
      min_uptime: 5000,
      env: {
        NODE_ENV: 'development',
        PORT: 4001,
        SERVICE_NAME: 'auth-service',
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_NAME: 'auth_db',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_EXPIRY: '24h',
        REFRESH_TOKEN_EXPIRY: '7d',
        BCRYPT_ROUNDS: '10',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 4001,
        SERVICE_NAME: 'auth-service',
        DB_HOST: 'auth-db.internal',
        DB_PORT: 5432,
        DB_NAME: 'auth_db',
        REDIS_HOST: 'redis.internal',
        REDIS_PORT: 6379,
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_EXPIRY: '24h',
        REFRESH_TOKEN_EXPIRY: '7d',
        BCRYPT_ROUNDS: '12',
      },
      error_file: './logs/auth-error.log',
      out_file: './logs/auth-out.log',
    },

    // User Service
    {
      name: 'user-service',
      script: './services/user/server.js',
      instances: 3,
      exec_mode: 'cluster',
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'development',
        PORT: 4002,
        SERVICE_NAME: 'user-service',
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_NAME: 'user_db',
        CACHE_HOST: 'localhost',
        CACHE_PORT: 6379,
        AVATAR_BUCKET: 'user-avatars',
        MAX_PROFILE_SIZE: '5MB',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 4002,
        SERVICE_NAME: 'user-service',
        DB_HOST: 'user-db.internal',
        DB_PORT: 5432,
        DB_NAME: 'user_db',
        CACHE_HOST: 'redis.internal',
        CACHE_PORT: 6379,
        AVATAR_BUCKET: 'prod-user-avatars',
        MAX_PROFILE_SIZE: '5MB',
      },
    },

    // Product Service
    {
      name: 'product-service',
      script: './services/product/server.js',
      instances: 4,
      exec_mode: 'cluster',
      max_memory_restart: '768M',
      env: {
        NODE_ENV: 'development',
        PORT: 4003,
        SERVICE_NAME: 'product-service',
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_NAME: 'product_db',
        ELASTICSEARCH_HOST: 'localhost',
        ELASTICSEARCH_PORT: 9200,
        IMAGE_BUCKET: 'product-images',
        THUMBNAIL_SIZE: '200x200',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 4003,
        SERVICE_NAME: 'product-service',
        DB_HOST: 'product-db.internal',
        DB_PORT: 5432,
        DB_NAME: 'product_db',
        ELASTICSEARCH_HOST: 'elasticsearch.internal',
        ELASTICSEARCH_PORT: 9200,
        IMAGE_BUCKET: 'prod-product-images',
        THUMBNAIL_SIZE: '200x200',
      },
    },

    // Order Service
    {
      name: 'order-service',
      script: './services/order/server.js',
      instances: 3,
      exec_mode: 'cluster',
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'development',
        PORT: 4004,
        SERVICE_NAME: 'order-service',
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_NAME: 'order_db',
        QUEUE_HOST: 'localhost',
        QUEUE_PORT: 5672,
        PAYMENT_SERVICE_URL: 'http://localhost:4005',
        INVENTORY_SERVICE_URL: 'http://localhost:4006',
        NOTIFICATION_SERVICE_URL: 'http://localhost:4007',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 4004,
        SERVICE_NAME: 'order-service',
        DB_HOST: 'order-db.internal',
        DB_PORT: 5432,
        DB_NAME: 'order_db',
        QUEUE_HOST: 'rabbitmq.internal',
        QUEUE_PORT: 5672,
        PAYMENT_SERVICE_URL: 'http://payment-service.internal:4005',
        INVENTORY_SERVICE_URL: 'http://inventory-service.internal:4006',
        NOTIFICATION_SERVICE_URL: 'http://notification-service.internal:4007',
      },
    },

    // Payment Service
    {
      name: 'payment-service',
      script: './services/payment/server.js',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'development',
        PORT: 4005,
        SERVICE_NAME: 'payment-service',
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_NAME: 'payment_db',
        STRIPE_API_KEY: process.env.STRIPE_API_KEY_DEV,
        STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET_DEV,
        PAYPAL_CLIENT_ID: process.env.PAYPAL_CLIENT_ID_DEV,
        PAYPAL_SECRET: process.env.PAYPAL_SECRET_DEV,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 4005,
        SERVICE_NAME: 'payment-service',
        DB_HOST: 'payment-db.internal',
        DB_PORT: 5432,
        DB_NAME: 'payment_db',
        STRIPE_API_KEY: process.env.STRIPE_API_KEY_PROD,
        STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET_PROD,
        PAYPAL_CLIENT_ID: process.env.PAYPAL_CLIENT_ID_PROD,
        PAYPAL_SECRET: process.env.PAYPAL_SECRET_PROD,
      },
    },

    // Inventory Service
    {
      name: 'inventory-service',
      script: './services/inventory/server.js',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'development',
        PORT: 4006,
        SERVICE_NAME: 'inventory-service',
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_NAME: 'inventory_db',
        CACHE_HOST: 'localhost',
        CACHE_PORT: 6379,
        LOW_STOCK_THRESHOLD: '10',
        REORDER_QUANTITY: '100',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 4006,
        SERVICE_NAME: 'inventory-service',
        DB_HOST: 'inventory-db.internal',
        DB_PORT: 5432,
        DB_NAME: 'inventory_db',
        CACHE_HOST: 'redis.internal',
        CACHE_PORT: 6379,
        LOW_STOCK_THRESHOLD: '10',
        REORDER_QUANTITY: '100',
      },
    },

    // Notification Service
    {
      name: 'notification-service',
      script: './services/notification/server.js',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'development',
        PORT: 4007,
        SERVICE_NAME: 'notification-service',
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_NAME: 'notification_db',
        QUEUE_HOST: 'localhost',
        QUEUE_PORT: 5672,
        SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
        TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
        TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
        PUSH_NOTIFICATION_KEY: process.env.PUSH_NOTIFICATION_KEY,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 4007,
        SERVICE_NAME: 'notification-service',
        DB_HOST: 'notification-db.internal',
        DB_PORT: 5432,
        DB_NAME: 'notification_db',
        QUEUE_HOST: 'rabbitmq.internal',
        QUEUE_PORT: 5672,
        SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
        TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
        TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
        PUSH_NOTIFICATION_KEY: process.env.PUSH_NOTIFICATION_KEY,
      },
    },

    // Analytics Service
    {
      name: 'analytics-service',
      script: './services/analytics/server.js',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 4008,
        SERVICE_NAME: 'analytics-service',
        CLICKHOUSE_HOST: 'localhost',
        CLICKHOUSE_PORT: 9000,
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
        KAFKA_BROKERS: 'localhost:9092',
        BATCH_SIZE: '1000',
        FLUSH_INTERVAL: '60000',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 4008,
        SERVICE_NAME: 'analytics-service',
        CLICKHOUSE_HOST: 'clickhouse.internal',
        CLICKHOUSE_PORT: 9000,
        REDIS_HOST: 'redis.internal',
        REDIS_PORT: 6379,
        KAFKA_BROKERS: 'kafka-1.internal:9092,kafka-2.internal:9092,kafka-3.internal:9092',
        BATCH_SIZE: '10000',
        FLUSH_INTERVAL: '30000',
      },
    },

    // Search Service
    {
      name: 'search-service',
      script: './services/search/server.js',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '768M',
      env: {
        NODE_ENV: 'development',
        PORT: 4009,
        SERVICE_NAME: 'search-service',
        ELASTICSEARCH_HOST: 'localhost',
        ELASTICSEARCH_PORT: 9200,
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
        INDEX_PREFIX: 'dev',
        CACHE_TTL: '3600',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 4009,
        SERVICE_NAME: 'search-service',
        ELASTICSEARCH_HOST: 'elasticsearch.internal',
        ELASTICSEARCH_PORT: 9200,
        REDIS_HOST: 'redis.internal',
        REDIS_PORT: 6379,
        INDEX_PREFIX: 'prod',
        CACHE_TTL: '7200',
      },
    },

    // Email Worker
    {
      name: 'email-worker',
      script: './workers/email/index.js',
      instances: 2,
      exec_mode: 'fork',
      max_memory_restart: '256M',
      cron_restart: '0 3 * * *', // Restart daily at 3 AM
      env: {
        NODE_ENV: 'development',
        WORKER_TYPE: 'email',
        QUEUE_HOST: 'localhost',
        QUEUE_PORT: 5672,
        QUEUE_NAME: 'email-queue',
        SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
        MAX_BATCH_SIZE: '100',
        RETRY_ATTEMPTS: '3',
      },
      env_production: {
        NODE_ENV: 'production',
        WORKER_TYPE: 'email',
        QUEUE_HOST: 'rabbitmq.internal',
        QUEUE_PORT: 5672,
        QUEUE_NAME: 'email-queue',
        SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
        MAX_BATCH_SIZE: '500',
        RETRY_ATTEMPTS: '5',
      },
    },

    // Image Processing Worker
    {
      name: 'image-worker',
      script: './workers/image/index.js',
      instances: 3,
      exec_mode: 'fork',
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        WORKER_TYPE: 'image',
        QUEUE_HOST: 'localhost',
        QUEUE_PORT: 5672,
        QUEUE_NAME: 'image-queue',
        S3_BUCKET: 'dev-images',
        S3_REGION: 'us-east-1',
        THUMBNAIL_SIZES: '100x100,200x200,400x400',
        IMAGE_QUALITY: '85',
      },
      env_production: {
        NODE_ENV: 'production',
        WORKER_TYPE: 'image',
        QUEUE_HOST: 'rabbitmq.internal',
        QUEUE_PORT: 5672,
        QUEUE_NAME: 'image-queue',
        S3_BUCKET: 'prod-images',
        S3_REGION: 'us-east-1',
        THUMBNAIL_SIZES: '100x100,200x200,400x400,800x800',
        IMAGE_QUALITY: '90',
      },
    },

    // Report Generator Worker
    {
      name: 'report-worker',
      script: './workers/report/index.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      cron_restart: '0 4 * * *', // Restart daily at 4 AM
      env: {
        NODE_ENV: 'development',
        WORKER_TYPE: 'report',
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_NAME: 'analytics_db',
        S3_BUCKET: 'dev-reports',
        REPORT_FORMATS: 'pdf,xlsx,csv',
      },
      env_production: {
        NODE_ENV: 'production',
        WORKER_TYPE: 'report',
        DB_HOST: 'analytics-db.internal',
        DB_PORT: 5432,
        DB_NAME: 'analytics_db',
        S3_BUCKET: 'prod-reports',
        REPORT_FORMATS: 'pdf,xlsx,csv',
      },
    },

    // Data Sync Worker
    {
      name: 'sync-worker',
      script: './workers/sync/index.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      cron_restart: '0 2 * * *', // Restart daily at 2 AM
      env: {
        NODE_ENV: 'development',
        WORKER_TYPE: 'sync',
        SOURCE_DB_HOST: 'localhost',
        SOURCE_DB_PORT: 5432,
        TARGET_DB_HOST: 'localhost',
        TARGET_DB_PORT: 5432,
        SYNC_INTERVAL: '300000', // 5 minutes
        BATCH_SIZE: '1000',
      },
      env_production: {
        NODE_ENV: 'production',
        WORKER_TYPE: 'sync',
        SOURCE_DB_HOST: 'source-db.internal',
        SOURCE_DB_PORT: 5432,
        TARGET_DB_HOST: 'target-db.internal',
        TARGET_DB_PORT: 5432,
        SYNC_INTERVAL: '60000', // 1 minute
        BATCH_SIZE: '10000',
      },
    },

    // Cache Warmer
    {
      name: 'cache-warmer',
      script: './workers/cache/warmer.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '256M',
      cron_restart: '0 */6 * * *', // Restart every 6 hours
      env: {
        NODE_ENV: 'development',
        WORKER_TYPE: 'cache-warmer',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
        API_BASE_URL: 'http://localhost:8000',
        WARM_ROUTES: '/api/products,/api/categories,/api/popular',
        WARM_INTERVAL: '1800000', // 30 minutes
      },
      env_production: {
        NODE_ENV: 'production',
        WORKER_TYPE: 'cache-warmer',
        REDIS_HOST: 'redis.internal',
        REDIS_PORT: 6379,
        API_BASE_URL: 'http://api-gateway.internal:8000',
        WARM_ROUTES: '/api/products,/api/categories,/api/popular,/api/trending',
        WARM_INTERVAL: '900000', // 15 minutes
      },
    },

    // Metrics Collector
    {
      name: 'metrics-collector',
      script: './monitoring/metrics-collector.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'development',
        PORT: 9090,
        PROMETHEUS_HOST: 'localhost',
        PROMETHEUS_PORT: 9091,
        COLLECT_INTERVAL: '10000', // 10 seconds
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 9090,
        PROMETHEUS_HOST: 'prometheus.internal',
        PROMETHEUS_PORT: 9091,
        COLLECT_INTERVAL: '5000', // 5 seconds
      },
    },

    // Health Check Service
    {
      name: 'health-check',
      script: './monitoring/health-check.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '128M',
      env: {
        NODE_ENV: 'development',
        PORT: 9091,
        CHECK_INTERVAL: '30000', // 30 seconds
        ALERT_WEBHOOK: process.env.SLACK_WEBHOOK_URL,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 9091,
        CHECK_INTERVAL: '15000', // 15 seconds
        ALERT_WEBHOOK: process.env.SLACK_WEBHOOK_URL,
      },
    },
  ],
};
