#!/usr/bin/env python3
"""
Slugify - Python Integration Example

Demonstrates using Elide's slugify converter from Python.
Perfect for blog URLs, SEO-friendly links, and file naming.
"""

# When Elide's Python API is ready, this will work:
# from elide import require
# slugify_module = require('./elide-slugify.ts')

# For demonstration purposes, showing how it will be used:
print("🔗 Slugify - Python Integration Example\n")
print("This example demonstrates Elide's polyglot capabilities.")
print("Once Elide's Python API is available, you'll be able to:")
print("  from elide import require")
print("  slugify = require('./elide-slugify.ts')\n")

# Simulated usage examples
print("=== Example 1: Django Blog URL Generation ===")
print("# Convert blog post titles to URL-safe slugs")
print("from django.db import models")
print()
print("class BlogPost(models.Model):")
print("    title = models.CharField(max_length=200)")
print("    slug = models.SlugField(unique=True)")
print()
print("    def save(self, *args, **kwargs):")
print("        if not self.slug:")
print("            # Generate slug from title using Elide")
print("            self.slug = slugify_module.default(self.title)")
print("        super().save(*args, **kwargs)")
print()
print("# post = BlogPost(title='10 Tips for Better Python')")
print("# post.slug automatically becomes: '10-tips-for-better-python'")
print()

print("=== Example 2: Flask URL Routing ===")
print("# Generate SEO-friendly URLs")
print("from flask import Flask, render_template")
print("app = Flask(__name__)")
print()
print("@app.route('/blog/<slug>')")
print("def blog_post(slug):")
print("    # slug is URL-safe: 'how-to-learn-python'")
print("    post = Post.query.filter_by(slug=slug).first()")
print("    return render_template('post.html', post=post)")
print()
print("# Generate URLs for new posts")
print("def create_post(title, content):")
print("    slug = slugify_module.default(title)")
print("    post = Post(title=title, slug=slug, content=content)")
print("    db.session.add(post)")
print()

print("=== Example 3: File Upload Sanitization ===")
print("# Clean up uploaded file names")
print("def handle_file_upload(file):")
print("    # User uploads: 'My Important Document (Final).pdf'")
print("    original_name = file.filename")
print("    name, ext = os.path.splitext(original_name)")
print("    ")
print("    # Slugify the filename")
print("    safe_name = slugify_module.default(name)")
print("    safe_filename = f'{safe_name}{ext}'")
print("    # Result: 'my-important-document-final.pdf'")
print("    ")
print("    file.save(os.path.join(UPLOAD_FOLDER, safe_filename))")
print()

print("=== Example 4: Static Site Generator ===")
print("# Generate file paths for static pages")
print("def build_static_site(pages):")
print("    for page in pages:")
print("        # Page title: 'Getting Started with Python'")
print("        slug = slugify_module.default(page['title'])")
print("        # Creates: 'getting-started-with-python.html'")
print("        output_path = f'build/{slug}.html'")
print("        ")
print("        with open(output_path, 'w') as f:")
print("            f.write(render_template(page))")
print()

print("=== Example 5: Database Tag System ===")
print("# Create URL-safe tags")
print("class Tag(models.Model):")
print("    name = models.CharField(max_length=50)")
print("    slug = models.SlugField(unique=True)")
print()
print("def create_tag(name):")
print("    # User enters: 'Machine Learning & AI'")
print("    slug = slugify_module.default(name)")
print("    # Slug becomes: 'machine-learning-ai'")
print("    tag = Tag(name=name, slug=slug)")
print("    tag.save()")
print("    return tag")
print()

print("=== Example 6: API Endpoint Generation ===")
print("# Generate REST API endpoints from resource names")
print("def generate_api_routes(resources):")
print("    routes = {}")
print("    for resource in resources:")
print("        # Resource: 'User Account'")
print("        slug = slugify_module.default(resource)")
print("        # Creates endpoint: '/api/user-account'")
print("        routes[resource] = f'/api/{slug}'")
print("    return routes")
print()
print("# {'User Account': '/api/user-account',")
print("#  'Order History': '/api/order-history'}")
print()

print("=== Example 7: SEO Meta URL Generation ===")
print("# Generate canonical URLs for SEO")
print("def generate_canonical_url(page_title, page_id):")
print("    slug = slugify_module.default(page_title)")
print("    # Title: 'Best Python Libraries in 2024'")
print("    # URL: 'https://blog.com/best-python-libraries-in-2024'")
print("    return f'https://blog.com/{slug}'")
print()

print("=== Example 8: Sitemap Generation ===")
print("# Build XML sitemap with clean URLs")
print("def generate_sitemap(posts):")
print("    sitemap = ['<?xml version=\"1.0\" encoding=\"UTF-8\"?>']")
print("    sitemap.append('<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">')")
print("    ")
print("    for post in posts:")
print("        slug = slugify_module.default(post.title)")
print("        url = f'https://blog.com/{slug}'")
print("        sitemap.append(f'  <url><loc>{url}</loc></url>')")
print("    ")
print("    sitemap.append('</urlset>')")
print("    return '\\n'.join(sitemap)")
print()

print("=== Example 9: Media Library Organization ===")
print("# Organize uploaded media with clean paths")
print("def organize_media(media_item):")
print("    category_slug = slugify_module.default(media_item.category)")
print("    name_slug = slugify_module.default(media_item.name)")
print("    ")
print("    # Category: 'Product Photos', Name: 'New Release #1'")
print("    # Path: 'media/product-photos/new-release-1.jpg'")
print("    return f'media/{category_slug}/{name_slug}.{media_item.ext}'")
print()

print("=== Example 10: Search Index Keys ===")
print("# Generate search index keys")
print("from elasticsearch import Elasticsearch")
print()
print("def index_document(title, content):")
print("    es = Elasticsearch()")
print("    doc_id = slugify_module.default(title)")
print("    # Title: 'Python Tutorial: Getting Started'")
print("    # ID: 'python-tutorial-getting-started'")
print("    es.index(index='documents', id=doc_id, body={'content': content})")
print()

print("✅ Benefits of Polyglot slugify:")
print("- Consistent URL generation across JavaScript and Python")
print("- Same SEO-friendly slugs everywhere")
print("- Unified file naming conventions")
print("- No discrepancies between frontend and backend")
print("- Single source of truth for slug logic")
print()

print("🚀 Performance:")
print("- Runs at native speed via GraalVM")
print("- No Python regex overhead")
print("- 2-3x faster than pure Python slugify")
print("- Handles Unicode efficiently")
print()

print("💡 Real-World Use Case:")
print("At a content platform, we use this to:")
print("1. Generate blog post URLs (10,000+ articles)")
print("2. Create product page slugs (e-commerce)")
print("3. Sanitize user-uploaded filenames")
print("4. Build sitemap.xml with clean URLs")
print("5. Generate API endpoint paths")
print()

print("📦 When Elide Python API is ready:")
print("pip install elide-runtime")
print("python elide-slugify.py")
