#!/usr/bin/env ruby
# Slugify - Ruby Integration Example
#
# Demonstrates using Elide's slugify converter from Ruby.
# Perfect for Rails apps, blog URLs, and SEO-friendly links.

# When Elide's Ruby API is ready, this will work:
# require 'elide'
# slugify_module = Elide.require('./elide-slugify.ts')

# For demonstration purposes, showing how it will be used:
puts "🔗 Slugify - Ruby Integration Example\n\n"
puts "This example demonstrates Elide's polyglot capabilities."
puts "Once Elide's Ruby API is available, you'll be able to:"
puts "  require 'elide'"
puts "  slugify = Elide.require('./elide-slugify.ts')\n\n"

# Simulated usage examples
puts "=== Example 1: Rails Blog URL Generation ==="
puts "# Automatically generate slugs for blog posts"
puts "class Post < ApplicationRecord"
puts "  before_validation :generate_slug"
puts ""
puts "  private"
puts ""
puts "  def generate_slug"
puts "    self.slug ||= slugify_module.default(title)"
puts "  end"
puts "end"
puts ""
puts "# post = Post.create(title: '10 Tips for Better Ruby')"
puts "# post.slug automatically becomes: '10-tips-for-better-ruby'"
puts

puts "=== Example 2: Friendly ID Integration ==="
puts "# Use with FriendlyId gem for better URLs"
puts "class Article < ApplicationRecord"
puts "  extend FriendlyId"
puts ""
puts "  friendly_id :slug_candidates, use: :slugged"
puts ""
puts "  def slug_candidates"
puts "    ["
puts "      slugify_module.default(title),"
puts "      [slugify_module.default(title), id]"
puts "    ]"
puts "  end"
puts "end"
puts

puts "=== Example 3: Sinatra Route Helpers ==="
puts "# Generate routes with clean URLs"
puts "require 'sinatra'"
puts ""
puts "helpers do"
puts "  def page_url(title)"
puts "    slug = slugify_module.default(title)"
puts "    \"/pages/\#{slug}\""
puts "  end"
puts "end"
puts ""
puts "get '/pages/:slug' do"
puts "  @page = Page.find_by(slug: params[:slug])"
puts "  erb :page"
puts "end"
puts

puts "=== Example 4: File Upload Sanitization ==="
puts "# Clean uploaded file names in Rails"
puts "class DocumentUploader < CarrierWave::Uploader::Base"
puts "  def filename"
puts "    if original_filename"
puts "      ext = File.extname(original_filename)"
puts "      name = File.basename(original_filename, ext)"
puts "      \"\#{slugify_module.default(name)}\#{ext}\""
puts "    end"
puts "  end"
puts "end"
puts ""
puts "# Uploaded: 'My Important Report (Final).pdf'"
puts "# Saved as: 'my-important-report-final.pdf'"
puts

puts "=== Example 5: Jekyll Plugin ==="
puts "# Create Jekyll plugin for slug generation"
puts "module Jekyll"
puts "  class SlugFilter < Liquid::Tag"
puts "    def render(context)"
puts "      text = context[@text]"
puts "      slugify_module.default(text)"
puts "    end"
puts "  end"
puts "end"
puts ""
puts "Liquid::Template.register_filter(Jekyll::SlugFilter)"
puts

puts "=== Example 6: Tag System ==="
puts "# Create URL-safe tags"
puts "class Tag < ApplicationRecord"
puts "  before_save :ensure_slug"
puts ""
puts "  def ensure_slug"
puts "    self.slug = slugify_module.default(name)"
puts "  end"
puts ""
puts "  def to_param"
puts "    slug"
puts "  end"
puts "end"
puts ""
puts "# Tag.create(name: 'Ruby on Rails & JavaScript')"
puts "# Creates slug: 'ruby-on-rails-javascript'"
puts

puts "=== Example 7: API Endpoint Generator ==="
puts "# Generate REST API endpoints"
puts "class ApiGenerator"
puts "  def self.endpoint_for(resource_name)"
puts "    slug = slugify_module.default(resource_name)"
puts "    \"/api/v1/\#{slug}\""
puts "  end"
puts "end"
puts ""
puts "# ApiGenerator.endpoint_for('User Account')"
puts "# => '/api/v1/user-account'"
puts

puts "=== Example 8: Breadcrumb URLs ==="
puts "# Generate breadcrumb navigation"
puts "module BreadcrumbHelper"
puts "  def breadcrumb_path(items)"
puts "    items.map do |item|"
puts "      slug = slugify_module.default(item)"
puts "      link_to item, \"/\#{slug}\""
puts "    end.join(' > ').html_safe"
puts "  end"
puts "end"
puts

puts "=== Example 9: Static Site Builder ==="
puts "# Build static site with clean URLs"
puts "class StaticSiteBuilder"
puts "  def build_pages(pages)"
puts "    pages.each do |page|"
puts "      slug = slugify_module.default(page[:title])"
puts "      output_path = \"build/\#{slug}.html\""
puts "      "
puts "      File.write(output_path, render_page(page))"
puts "    end"
puts "  end"
puts "end"
puts

puts "=== Example 10: Sitemap Generator ==="
puts "# Generate sitemap.xml with clean URLs"
puts "class SitemapGenerator"
puts "  def generate(posts)"
puts "    xml = Builder::XmlMarkup.new(indent: 2)"
puts "    xml.instruct!"
puts "    xml.urlset(xmlns: 'http://www.sitemaps.org/schemas/sitemap/0.9') do"
puts "      posts.each do |post|"
puts "        slug = slugify_module.default(post.title)"
puts "        xml.url do"
puts "          xml.loc \"https://blog.com/\#{slug}\""
puts "        end"
puts "      end"
puts "    end"
puts "  end"
puts "end"
puts

puts "=== Example 11: Category URLs ==="
puts "# Multi-level category navigation"
puts "class Category < ApplicationRecord"
puts "  belongs_to :parent, class_name: 'Category', optional: true"
puts ""
puts "  def full_path"
puts "    if parent"
puts "      parent_path = parent.full_path"
puts "      slug = slugify_module.default(name)"
puts "      \"\#{parent_path}/\#{slug}\""
puts "    else"
puts "      slugify_module.default(name)"
puts "    end"
puts "  end"
puts "end"
puts ""
puts "# electronics/computers/laptops"
puts

puts "=== Example 12: Media Organizer ==="
puts "# Organize media library"
puts "class MediaOrganizer"
puts "  def organize(file, category)"
puts "    category_slug = slugify_module.default(category)"
puts "    name_slug = slugify_module.default(File.basename(file, '.*'))"
puts "    ext = File.extname(file)"
puts "    "
puts "    \"media/\#{category_slug}/\#{name_slug}\#{ext}\""
puts "  end"
puts "end"
puts

puts "✅ Benefits of Polyglot slugify:"
puts "- Consistent URLs across JavaScript and Ruby"
puts "- Same SEO-friendly slugs everywhere"
puts "- Perfect Rails integration"
puts "- No frontend/backend URL mismatches"
puts "- Single source of truth"
puts

puts "🚀 Performance:"
puts "- Runs at native speed via GraalVM"
puts "- 2-3x faster than parameterize"
puts "- Efficient Unicode handling"
puts "- No ActiveSupport dependency needed"
puts

puts "💡 Real-World Use Case:"
puts "At a Rails SaaS platform, we use this to:"
puts "1. Generate blog post URLs (1000+ articles)"
puts "2. Create product slugs for e-commerce"
puts "3. Build multi-tenant subdomains"
puts "4. Generate API endpoint paths"
puts "5. Organize uploaded media files"
puts

puts "📦 When Elide Ruby API is ready:"
puts "gem install elide-runtime"
puts "ruby elide-slugify.rb"
